language: Python
dist: trusty
sudo: Required

python:
- '3.5'

before_install:
- pip install -U pip
- pip install -U setuptools
- pip install -r requirements.txt

script:
- make html

after_success:
- rm -rf .git/
- git init
- git config user.name "PyconID"
- git config user.email "pyconid@pycon.id"
- git config --global push.default simple
- git remote add origin https://$GITHUB_TOKEN@github.com/pyconid/pyconid2019
- make github

branches:
  only:
  - master
